FROM mysql:latest

# root user password
ENV MYSQL_ALLOW_EMPTY_PASSWORD=1

# Create a database and user
ENV MYSQL_DATABASE=accounting_manager

# Copy your database export file into the container
COPY accounting_manager.sql /docker-entrypoint-initdb.d/

# Expose the MySQL port
EXPOSE 3306
