FROM eclipse-temurin:17-jdk as bank_statement_engine

RUN apt-get update \
    && apt-get install -y sudo \
    && apt-get update \
    && sudo apt install -y tesseract-ocr \
    && sudo apt-get install tesseract-ocr-fra \
    && mkdir -p /tmp/bank_statement_engine \
    && mkdir -p /tmp/bank_statement_engine/source_xml \
    && mkdir -p /tmp/bank_statement_engine/transformed_xml